development:
  solr_core_parent: ""
  solr_core_name:   umrdr-testing
  solr_home:        <%= ENV['SOLR_HOME']      || "/quod-dev/idx/h/hydra-solr" %>
  solr_admin_url:   <%= ENV['SOLR_ADMIN_URL'] || "http://localhost:8080/tomcat/quod-dev/solr-hydra/admin" %>
  fedora_url:       localhost:8080/fedora/rest
  fedora_node_path: umrdr-testing

testing:
  solr_admin_url:   <%= ENV['SOLR_ADMIN_URL'] || "http://localhost:8080/tomcat/quod-dev/solr-hydra/admin" %>
  fedora_url:       localhost:8080/fedora/rest
